DROP TABLE IF EXISTS Drinks;
DROP TABLE IF EXISTS Members;
DROP TABLE IF EXISTS Orders;

CREATE TABLE Drinks (
	Id INT NOT NULL IDENTITY,
	DrinkType NVARCHAR(50) NOT NULL,
	Price DECIMAL NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE Members (
	Id INT NOT NULL IDENTITY,
	Firstname NVARCHAR(50) NOT NULL,
	Lastname NVARCHAR(50) NOT NULL,
	Address NVARCHAR(250) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	Wallet DECIMAL NOT NULL,
	IsOwner NVARCHAR(20) NOT NULL,
	CreatedDate NVARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE Orders (
	Id INT NOT NULL IDENTITY,
	CreatedDate NVARCHAR(100) NOT NULL,
	Member NVARCHAR(250) NOT NULL,
	MemberID INT NOT NULL,
	Drinks NVARCHAR(100) NOT NULL,
	PriceTotal DECIMAL NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (MemberID) REFERENCES Members(Id)
);